# Generated by Django 4.2.20 on 2025-05-07 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['date', 'meal_type']},
        ),
        migrations.RenameField(
            model_name='mealfeedback',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mealfeedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='messleave',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='messleave',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='specialmealrequest',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='specialmealrequest',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='specialmealrequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
        migrations.AddField(
            model_name='specialmealrequest',
            name='dietary_requirements',
            field=models.TextField(default='None', help_text='Specific dietary requirements'),
        ),
        migrations.AlterField(
            model_name='mealfeedback',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.menu'),
        ),
        migrations.AlterField(
            model_name='mealfeedback',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mealfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.TextField(help_text='List of food items for this meal'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='messleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mess_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messleave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='messleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialmealrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialmealrequest',
            name='reason',
            field=models.TextField(help_text='Reason for special meal request'),
        ),
        migrations.AlterField(
            model_name='specialmealrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='specialmealrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('day', 'meal_type', 'date')},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_by',
        ),
    ]
